/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppInvoiceIndexRouteImport } from './routes/app/invoice/index'
import { Route as AppInvoiceActionRouteImport } from './routes/app/invoice/$action'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoiceIndexRoute = AppInvoiceIndexRouteImport.update({
  id: '/invoice/',
  path: '/invoice/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoiceActionRoute = AppInvoiceActionRouteImport.update({
  id: '/invoice/$action',
  path: '/invoice/$action',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/invoice/$action': typeof AppInvoiceActionRoute
  '/app/invoice': typeof AppInvoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/invoice/$action': typeof AppInvoiceActionRoute
  '/app/invoice': typeof AppInvoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/invoice/$action': typeof AppInvoiceActionRoute
  '/app/invoice/': typeof AppInvoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/invoice/$action' | '/app/invoice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/invoice/$action' | '/app/invoice'
  id: '__root__' | '/' | '/app' | '/app/invoice/$action' | '/app/invoice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/invoice/': {
      id: '/app/invoice/'
      path: '/invoice'
      fullPath: '/app/invoice'
      preLoaderRoute: typeof AppInvoiceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoice/$action': {
      id: '/app/invoice/$action'
      path: '/invoice/$action'
      fullPath: '/app/invoice/$action'
      preLoaderRoute: typeof AppInvoiceActionRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppInvoiceActionRoute: typeof AppInvoiceActionRoute
  AppInvoiceIndexRoute: typeof AppInvoiceIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppInvoiceActionRoute: AppInvoiceActionRoute,
  AppInvoiceIndexRoute: AppInvoiceIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
