# Generated by Django 5.2.4 on 2025-08-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='accounting.account'),
        ),
    ]
