# Generated by Django 5.2.4 on 2025-07-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='parent_account',
            new_name='parent',
        ),
    ]
