# Generated by Django 5.2.4 on 2025-07-29 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_parent_account_account_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=99, primary_key=True, serialize=False),
        ),
    ]
