# Generated by Django 5.2.4 on 2025-07-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_pricelist_uom_product_cover_image_productprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_uom',
        ),
    ]
