# Generated by Django 5.2.4 on 2025-07-20 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_product_stock_uom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_stock',
            new_name='maintain_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.uom'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=200, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
