# Generated by Django 5.2.4 on 2025-07-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_profiles', to='accounting.company'),
        ),
    ]
