# Generated by Django 5.2.4 on 2025-07-21 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_posprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 20, 59, 2, 704880, tzinfo=datetime.timezone.utc)),
        ),
    ]
