# Generated by Django 5.2.4 on 2025-07-21 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_invoices', to='point_of_sale.branch'),
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 21, 4, 16, 341492, tzinfo=datetime.timezone.utc)),
        ),
    ]
