# Generated by Django 5.2.4 on 2025-07-21 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_alter_posinvoice_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posinvoice',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 21, 35, 8, 809853, tzinfo=datetime.timezone.utc)),
        ),
    ]
