# Generated by Django 5.2.4 on 2025-07-22 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_posinvoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('return', 'Return'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('credit_note_issued', 'Credit Note Issued')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 8, 48, 48, 657448, tzinfo=datetime.timezone.utc)),
        ),
    ]
