# Generated by Django 5.2.4 on 2025-07-28 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_posinvoice_status_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 7, 47, 51, 511116, tzinfo=datetime.timezone.utc)),
        ),
    ]
