# Generated by Django 5.2.4 on 2025-08-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 11, 15, 14, 445191, tzinfo=datetime.timezone.utc)),
        ),
    ]
