# Generated by Django 5.2.4 on 2025-09-09 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0013_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 9, 9, 28, 58, 870614, tzinfo=datetime.timezone.utc)),
        ),
    ]
