# Generated by Django 5.2.4 on 2025-09-18 20:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_account_parent_account_account_parent'),
        ('point_of_sale', '0014_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posinvoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 20, 15, 33, 690033, tzinfo=datetime.timezone.utc)),
        ),
    ]
