# Generated by Django 5.2.4 on 2025-09-18 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0015_posinvoice_company_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 20, 19, 41, 561555, tzinfo=datetime.timezone.utc)),
        ),
    ]
