# Generated by Django 5.2.4 on 2025-07-29 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0015_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 10, 25, 30, 189985, tzinfo=datetime.timezone.utc)),
        ),
    ]
