# Generated by Django 5.2.4 on 2025-09-19 00:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_account_parent_account_account_parent'),
        ('point_of_sale', '0016_alter_posinvoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.company'),
        ),
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 19, 0, 0, 44, 88069, tzinfo=datetime.timezone.utc)),
        ),
    ]
