# Generated by Django 5.2.4 on 2025-07-29 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0017_alter_posinvoice_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posinvoice',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 11, 35, 59, 419181, tzinfo=datetime.timezone.utc)),
        ),
    ]
